# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-20 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleprestamo',
            old_name='Recurso_detalle',
            new_name='Libro_detalle',
        ),
    ]
