# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-20 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_auto_20190520_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidente',
            old_name='Recurso',
            new_name='Libro',
        ),
    ]
